###
GET http://localhost:4004/odata/v4/catalog/
###
POST http://localhost:4004/odata/v4/catalog/loadAppsFromSAP
Content-Type: application/json

{}
###
POST http://localhost:4004/odata/v4/catalog/loadServicesFromSAP
Content-Type: application/json

{}
###
GET http://localhost:4004/odata/v4/catalog/Details
  ?$count=true
  &$select=AppName,RequiredODataServices
  &$expand=RequiredODataServices
  &$top=10

###
GET http://localhost:4004/odata/v4/catalog/RequiredODataServices
  ?$count=true
  &$top=10
Content-Type: application/json
###
GET http://localhost:4004/odata/v4/catalog/RequiredODataServices
    ?$apply=groupby((fioriId,releaseId,NameSpace,TechnicalName),aggregate(serviceCounter with sum as numberUsages))
